#!/bin/bash
#made this to try and diagnose system freezes it will log every recent addition
#to /var/log every single minute if system freezes reboot and check the last entries
cd /var/log
rm -rf /var/log/ll.old
mv /var/log/ll /var/log/ll.old
mkdir -p /var/log/ll


while :
do
mv /var/log/ll/lastlog.4 /var/log/ll/lastlog.5 
mv /var/log/ll/lastlog.3 /var/log/ll/lastlog.4
mv /var/log/ll/lastlog.2 /var/log/ll/lastlog.3 
mv /var/log/ll/lastlog.1 /var/log/ll/lastlog.2 
mv /var/log/ll/lastlog /var/log/ll/lastlog.1 
tail $(file `ls -t |head -8` |grep -i ASCII | awk '{print $1}' | sed -e 's/:/\ /g') > /var/log/ll/lastlog
#uncomment nvidia line if you have a nvidia card
#nvidia-smi -q -d temperature >> /var/log/ll/lastlog
free -m >> /var/log/ll/lastlog
ps aux | awk '{mem[$11]+=int($6/1024)}; {cpuper[$11]+=$3};{memper[$11]+=$4}; END {for (i in mem) {print cpuper[i]"% ",memper[i]"% ",mem[i]" MB ",i}}' | sort -k3nr | head -n 10 >> /var/log/ll/lastlog
sleep 60
 done


